permalink: :year-:month-:day-:title 

highlighter: pygments
markdown: kramdown

title : RTPI Chautauqua County Natural History Atlas
tagline: 
author : 
  name : Orbitist Support
  email : support@orbitist.com
  github : Orbitist
  twitter : TheOrbitist
  web : http://www.orbitist.com

production_url : orbitist.com/rtpi

baseurl : http://orbitist.com/rtpi
        
analytics :
  google : 
    tracking_id : ''


authors:
  ngunner:
    name: Nicholas Gunner
    display_name: Nicholas Gunner
    bio: Founder of Orbitist. New Media Manager at SUNY Fredonia. Multimedia Storyteller.
    image: http://orbitist.s3.amazonaws.com/_toplevel/images/profile-images/ngunner.jpg
    email: gunnernr@gmail.com
    web: http://www.nicholasgunner.com
    twitter: nicholas_gunner
    github: ngunner

  
timezone : America/New_York